services:
  - type: web
    name: beatanimebot
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URI
        sync: false
      - key: DATABASE_NAME
        value: BeatAnimeBot
      - key: CHANNELS
        sync: false
      - key: ADMINS
        sync: false
      - key: FORCE_SUB_CHANNELS
        value: "0"
      - key: LOG_CHANNEL
        value: "0"
      - key: SUPPORT_CHAT
        value: Beat_Anime_Ocean
      - key: UPDATES_CHANNEL
        value: beatAnime
      - key: BOT_PICS
        value: https://telegra.ph/file/d8d2e9cc6d60741c7e77d.jpg
      - key: PROTECT_CONTENT
        value: "True"
      - key: HIDE_CAPTION
        value: "False"
      - key: AUTO_DELETE_TIME
        value: "300"
      - key: REQUEST_FSUB
        value: "False"
      - key: WORKERS
        value: "4"
