services:
  - type: web
    name: telegram-bot
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URI
        sync: false
      - key: DATABASE_NAME
        value: Beat-Link-Provider
      - key: CHANNELS
        value: "0"
      - key: ADMINS
        sync: false
      - key: FORCE_SUB_CHANNELS
        value: "0"
      - key: LOG_CHANNEL
        value: "0"
      - key: SUPPORT_CHAT
        value: ""
      - key: UPDATES_CHANNEL
        value: ""
      - key: BOT_PICS
        value: https://ibb.co/k6BPTc45
      - key: PROTECT_CONTENT
        value: "True"
      - key: HIDE_CAPTION
        value: "False"
      - key: AUTO_DELETE_TIME
        value: "0"
      - key: REQUEST_FSUB
        value: "False"
      - key: WORKERS
        value: "4"
      - key: PORT
        generateValue: true
